title: 北京加膜
company: 北京佳膜环保科技有限公司
tel: 
address: 
com_detail: <p></p>
collections:
 about:
   name: 关于我们
   output: true
 anli:
   name: 应用案例
   output: true
 product:
   name: 核心产品
   output: true
 tech:
   name: 核心技术
   output: true
baseurl: "" # the subpath of your site, e.g. /blog 
imgurl: "http://img.xindapin.cn/jiamo/"
#port:    4000
#host:    192.168.88.101
